// Pickle Master — Bilingual String Definitions
// EN = English, ZH = Traditional Chinese (Hong Kong)

const LANG = {
  EN: {
    // Nav
    nav_home: 'HOME', nav_member: 'MEMBER', nav_book: 'BOOK',
    nav_social: 'SOCIAL', nav_private: 'PRIVATE', nav_contact: 'CONTACT',
    nav_login: 'Log In', nav_account: 'Account', nav_cart: 'Cart',
    nav_logout: 'Log Out',
    promo_banner: 'OPENING SPECIAL — JOIN THE FOUNDING MEMBER WAITLIST',

    // Home
    home_eyebrow: 'Hong Kong · Est. 2026',
    home_hero_title: "Premier Indoor\nPickleball Courts",
    home_hero_sub: "Hong Kong's most dedicated pickleball club. Where craft meets court.",
    home_cta_book: 'Book Now',
    home_cta_member: 'Become a Member',
    home_how_title: 'How to Start',
    home_step1_title: 'Join as Member',
    home_step1_desc: 'Enjoy priority booking, member rates, and zero guest fees.',
    home_step2_title: 'First Booking',
    home_step2_desc: 'Book your court, class, or social play in under a minute.',
    home_step3_title: 'Coaching',
    home_step3_desc: 'Learn and grow with internationally certified coaches.',
    home_step4_title: 'Kids',
    home_step4_desc: 'Play, learn, and have fun with family and friends.',
    home_lessons_title: 'Lessons',
    home_academy_title: 'Academy',
    home_academy_desc: 'Level up through structured programs for newcomers to intermediates.',
    home_private_title: 'Private Lesson',
    home_private_desc: 'All the attention you need with a structured program.',
    home_friends_title: 'Friends Private',
    home_friends_desc: 'Improve your gameplay, tailored to your needs.',
    home_players: '4–8 players with internationally certified coach',
    home_1on1: '1-on-1 with internationally certified coach',
    home_upto6: 'Up to 6-on-1 with internationally certified coach',
    home_know_more: 'Know More',
    home_testimonials_title: 'What Members Say',
    home_101_title: 'Pickleball 101',
    home_101_sub: 'New to the game? Here are the basics.',
    home_rule1_title: '1. Basic Rules',
    home_rule1: 'Played to 11 points, win by 2. Singles (1v1) or doubles (2v2). Only the serving side can score.',
    home_rule2_title: '2. Serve',
    home_rule2: 'Hit underhand, diagonally across the court. Ball must clear the non-volley zone.',
    home_rule3_title: '3. Two-Bounce Rule',
    home_rule3: 'The ball must bounce once on each side before volleys are allowed.',
    home_rule4_title: '4. Kitchen Rule',
    home_rule4: 'No volleys while standing in the kitchen (non-volley zone).',
    home_rule5_title: '5. End of a Rally',
    home_rule5: 'Ball goes out, hits the net, or bounces twice before being returned.',
    home_about_title: 'Pickle Master',
    home_about: 'Pickle Master (匹匠) is a premium indoor pickleball club in Hong Kong, Est. 2026. We fuse the craft of play with the energy of community — a dedicated space where every level of player is welcome. Sport, style, and great people. That is what we are about.',
    home_address: 'Address',
    home_address_val: 'We Go Mall, Ma On Shan, New Territories, Hong Kong',
    home_tagline: "Everyone's Invited. Game On.",

    // Member
    member_title: 'Membership',
    member_hero: 'Play More. Pay Less.',
    member_sub: 'Our membership is your ticket to the Pickle Master community. Priority courts, member rates, and a growing network of players who mix sport with style.',
    member_no_commit: 'No minimum commitment — start with one month.',
    member_dink_title: 'DINK',
    member_dink_price: '$380 / month',
    member_flex_title: 'FLEX',
    member_flex_price: '$280 / month',
    member_nonmember_title: 'NON-MEMBER',
    member_join: 'Join',
    member_waitlist: 'Join Waitlist',
    member_full: 'Currently Full',
    member_how_title: 'How to Book',
    member_how_sub: 'One minute to secure your court, class, or social play.',
    member_courts_title: 'Our Courts',
    member_court1: 'Court 1',
    member_court2: 'Court 2',
    member_book_now: 'Book Now',
    // Membership features
    mf_d1: 'Priority booking — 14 days ahead (peak & non-peak)',
    mf_d2: '10% off court bookings + 20% off social play',
    mf_d3: 'Pro-level paddle trial during sessions',
    mf_d4: 'Priority access to social events & gatherings',
    mf_d5: 'Zero guest fees',
    mf_d6: 'Buy one, get one on beverages (per session, non-alcoholic)',
    mf_d7: 'Book 2 consecutive hours',
    mf_d8: 'Changing rooms, private locker, AI game analysis, leagues & tournaments',
    mf_d9: 'Free DINK training corner access',
    mf_f1: 'Priority booking — 7 days ahead (peak & non-peak)',
    mf_f2: '10% off court bookings + 20% off social play',
    mf_f3: 'Pro-level paddle trial during sessions',
    mf_f4: 'Priority access to social events & gatherings',
    mf_f5: 'Zero guest fees',
    mf_f6: 'Changing rooms, private locker, AI game analysis, leagues & tournaments',
    mf_f7: 'Free DINK training corner access',
    mf_nm1: 'Booking — 3 days ahead (peak), 7 days ahead (non-peak)',
    mf_nm2: '$20 paddle rental fee',
    mf_nm3: 'Standard booking rates',
    mf_nm4: '$50 guest fee per guest',
    mf_nm5: 'Changing room access',

    // Book
    book_title: 'Book',
    book_hero: 'Reserve Your Court',
    book_select_court: 'Select Court',
    book_select_type: 'Session Type',
    book_select_date: 'Select Date',
    book_select_time: 'Available Times',
    book_court1: 'Court 1',
    book_court2: 'Court 2',
    book_add_cart: 'Add to Cart',
    book_peak: 'PEAK',
    book_nonpeak: 'NON-PEAK',
    book_peak_desc: 'Mon–Fri 6pm–10pm · Sat, Sun & PH 10am–10pm',
    book_nonpeak_desc: 'Mon–Fri 10am–6pm',
    book_private_class: 'PRIVATE CLASS',
    book_private_class_desc: 'Max 6 with internationally certified coach',
    book_social: 'SOCIAL PLAY',
    book_social_desc: 'Casual games, meet new friends',
    book_social_vip: 'SOCIAL PLAY (Member)',
    book_trial: 'TRIAL CLASS',
    book_trial_desc: 'Max 8 students per class (Age 10+)',
    book_beginner: 'BEGINNER COURSE',
    book_beginner_desc: '4-session course with certified coach',
    book_member_price: 'Member Rate',
    book_per_session: '/ session',
    book_confirm: 'Confirm Booking',
    book_guest_fee: '+ $50 guest fee applies (non-members)',
    book_member_badge: 'MEMBER',
    book_available: 'Available',
    book_limited: 'Limited',
    book_full: 'Full',
    book_cart_added: 'Added to cart',

    // Social
    social_title: 'Social Play',
    social_hero: 'Meet. Play. Connect.',
    social_desc: 'Social play is the heart of Pickle Master — casual, competitive, and always fun. Show up, get matched, make friends. No partner needed.',
    social_how_title: 'How Social Play Works',
    social_s1_title: 'Show Up',
    social_s1: 'Book your social play slot. No partner required — we match you on court.',
    social_s2_title: 'Get Matched',
    social_s2: 'We group players by level for balanced, fun games.',
    social_s3_title: 'Play & Connect',
    social_s3: 'Meet new people, build your network, enjoy the game.',
    social_price_title: 'Social Play Rates',
    social_nonmember: 'Non-Member',
    social_member: 'Member Rate',
    social_book: 'Book Social Play',

    // Private
    private_title: 'Private & Corporate',
    private_hero: 'Private Events & Corporate Bookings',
    private_desc: 'Trusted by top organisations for team-building events, corporate outings, and private celebrations. We handle everything — court, coaching, catering coordination.',
    private_trusted: 'Trusted By',
    private_what_title: 'What We Offer',
    private_w1_title: 'Full Court Hire',
    private_w1: 'Exclusive court access for your group — up to 12 players per session.',
    private_w2_title: 'Coached Sessions',
    private_w2: 'Internationally certified coaches run structured clinics for all levels.',
    private_w3_title: 'Custom Events',
    private_w3: 'Tournaments, leagues, and branded experiences for your organisation.',
    private_enquire: 'Enquire Now',
    private_class_price: 'from $1,060 / session',

    // Contact
    contact_title: 'Contact',
    contact_hero: 'Get in Touch',
    contact_name: 'Your Name',
    contact_email: 'Email Address',
    contact_subject: 'Subject',
    contact_message: 'Message',
    contact_send: 'Send Message',
    contact_address_title: 'Location',
    contact_address: 'We Go Mall, Ma On Shan, New Territories, Hong Kong',
    contact_hours_title: 'Hours',
    contact_hours: 'Mon–Fri: 10:00–22:00\nSat, Sun & PH: 10:00–22:00',
    contact_follow: 'Follow Us',
    contact_sent: 'Message sent. We will be in touch shortly.',

    // Login / Account
    login_title: 'Log In',
    login_email: 'Email',
    login_password: 'Password',
    login_submit: 'Log In',
    login_register: 'Create Account',
    login_forgot: 'Forgot password?',
    login_no_account: "Don't have an account?",
    register_title: 'Create Account',
    register_name: 'Full Name',
    register_email: 'Email',
    register_password: 'Password',
    register_submit: 'Create Account',
    register_have_account: 'Already have an account?',
    account_welcome: 'Welcome back',
    account_member_status: 'Membership',
    account_bookings: 'My Bookings',
    account_no_bookings: 'No upcoming bookings.',
    account_book_now: 'Book a Session',
    account_details: 'Account Details',
    account_membership: 'Membership Details',
    account_upgrade: 'Upgrade Membership',

    // Cart
    cart_title: 'Cart',
    cart_empty: 'Your cart is empty.',
    cart_total: 'Total',
    cart_checkout: 'Checkout',
    cart_remove: 'Remove',
    cart_guest_note: 'Guest fee of $50 per session applies for non-members.',
    cart_member_disc: 'Member discount applied.',
    checkout_title: 'Checkout',
    checkout_name: 'Cardholder Name',
    checkout_card: 'Card Number',
    checkout_expiry: 'Expiry',
    checkout_cvc: 'CVC',
    checkout_pay: 'Pay Now',
    checkout_success: 'Booking Confirmed!',
    checkout_success_sub: 'A confirmation has been sent to your email.',

    // More nav
    nav_more: 'More',
    nav_coaches: 'Coaches',
    nav_tournament: 'Tournament',
    nav_shop: 'Shop',
    nav_faq: 'FAQ',

    // Coaches
    coaches_title: 'Coaches',
    coaches_hero: 'Meet the Team',
    coaches_sub: 'Our coaches are internationally certified, passionate about the game, and dedicated to helping every player grow.',
    coaches_book: 'Book a Session',
    coaches_inhouse: 'In-house Coach',
    coaches_flexible: 'Flexible Coach',
    coaches_guest: 'Guest Coach',

    // Tournament
    tournament_title: 'Tournament',
    tournament_hero: 'Compete. Grow. Win.',
    tournament_sub: 'Pickle Master hosts regular in-house tournaments and leagues open to all skill levels. Sign up, compete, and track your progress.',
    tournament_upcoming: 'Upcoming Events',
    tournament_register: 'Register',
    tournament_full: 'Full',
    tournament_open: 'Open',
    tournament_members_only: 'Members Only',
    tournament_format: 'Format',
    tournament_level: 'Level',
    tournament_date: 'Date',
    tournament_fee: 'Entry Fee',

    // Shop
    shop_title: 'Shop',
    shop_hero: 'Gear Up',
    shop_sub: 'Official Pickle Master merchandise — paddles, apparel, and accessories. Member discount applies.',
    shop_add: 'Add to Cart',
    shop_sold_out: 'Sold Out',
    shop_member_price: 'Member Price',
    shop_cat_paddles: 'Paddles',
    shop_cat_apparel: 'Apparel',
    shop_cat_accessories: 'Accessories',
    shop_all: 'All',

    // FAQ
    faq_title: 'FAQ',
    faq_hero: 'Frequently Asked Questions',
    faq_sub: 'Everything you need to know before your first visit.',
    faq_still: 'Still have questions?',
    faq_contact: 'Contact Us',

    // Footer
    footer_about: 'Pickle Master (匹匠) is Hong Kong\'s premier indoor pickleball club. Est. 2026.',
    footer_links: 'Quick Links',
    footer_legal: 'Legal',
    footer_privacy: 'Privacy Policy',
    footer_terms: 'Terms of Service',
    footer_cancel: 'Cancellation Policy',
    footer_rights: '2026 Pickle Master. All rights reserved.',
    footer_payment: 'We accept',
  },

  ZH: {
    // Nav
    nav_home: '主頁', nav_member: '會員', nav_book: '預訂',
    nav_social: '社交賽', nav_private: '私人活動', nav_contact: '聯絡我們',
    nav_login: '登入', nav_account: '帳戶', nav_cart: '購物車',
    nav_logout: '登出',
    promo_banner: '開幕優惠 — 立即加入創辦會員候補名單',

    // Home
    home_eyebrow: '香港 · 2026年成立',
    home_hero_title: '香港頂級\n室內匹克球場',
    home_hero_sub: '香港最專注的匹克球俱樂部。工匠精神，盡顯球場。',
    home_cta_book: '立即預訂',
    home_cta_member: '成為會員',
    home_how_title: '如何開始',
    home_step1_title: '加入會員',
    home_step1_desc: '享受優先預訂、會員優惠及免賓客費。',
    home_step2_title: '首次預訂',
    home_step2_desc: '一分鐘內完成球場、課程或社交賽預訂。',
    home_step3_title: '教練課程',
    home_step3_desc: '與國際認證教練一同學習、成長。',
    home_step4_title: '兒童課程',
    home_step4_desc: '與家人朋友一同玩樂、學習、成長。',
    home_lessons_title: '課程',
    home_academy_title: '訓練學院',
    home_academy_desc: '為初學者至中級球員提供系統化訓練課程。',
    home_private_title: '私人課程',
    home_private_desc: '專屬一對一系統化指導。',
    home_friends_title: '朋友私人課',
    home_friends_desc: '度身訂造的課程，提升你的球技。',
    home_players: '4–8名學員，配備國際認證教練',
    home_1on1: '一對一，配備國際認證教練',
    home_upto6: '最多6對1，配備國際認證教練',
    home_know_more: '了解更多',
    home_testimonials_title: '會員心聲',
    home_101_title: '匹克球入門',
    home_101_sub: '初次接觸？以下是基本規則。',
    home_rule1_title: '1. 基本規則',
    home_rule1: '比賽打至11分，須以2分差勝出。單打（1對1）或雙打（2對2）。只有發球方可得分。',
    home_rule2_title: '2. 發球',
    home_rule2: '須以下手方式對角發球，球必須越過對方的禁區。',
    home_rule3_title: '3. 雙跳規則',
    home_rule3: '球須在雙方各彈跳一次後，才可進行截擊。',
    home_rule4_title: '4. 廚房規則',
    home_rule4: '站在廚房（禁區）內不可進行截擊。',
    home_rule5_title: '5. 回合結束',
    home_rule5: '球出界、落網或在同側彈跳兩次而未被回擊。',
    home_about_title: 'Pickle Master 匹匠',
    home_about: '匹匠（Pickle Master）是香港於2026年成立的頂級室內匹克球俱樂部。我們將球技與社群活力融合，為每一位球員打造專屬空間。運動、風格、良師益友——這就是我們的理念。',
    home_address: '地址',
    home_address_val: '新界馬鞍山 We Go Mall',
    home_tagline: '歡迎所有人。開球！',

    // Member
    member_title: '會員計劃',
    member_hero: '打得更多，花得更少。',
    member_sub: '會籍是您進入匹匠社群的門票。優先訂場、會員優惠及不斷擴展的球友網絡。',
    member_no_commit: '無最低承諾期，由一個月開始。',
    member_dink_title: 'DINK 會員',
    member_dink_price: '$380 / 月',
    member_flex_title: 'FLEX 會員',
    member_flex_price: '$280 / 月',
    member_nonmember_title: '非會員',
    member_join: '立即加入',
    member_waitlist: '加入候補名單',
    member_full: '名額已滿',
    member_how_title: '如何預訂',
    member_how_sub: '一分鐘內輕鬆完成首次預訂。',
    member_courts_title: '我們的球場',
    member_court1: '1號球場',
    member_court2: '2號球場',
    member_book_now: '立即預訂',
    mf_d1: '優先預訂——提前14天（繁忙及非繁忙時段）',
    mf_d2: '所有訂場享9折 + 社交賽享8折',
    mf_d3: '訓練期間可試用專業球拍',
    mf_d4: '優先參加社交活動及內部聚會',
    mf_d5: '零賓客費',
    mf_d6: '每節課買一送一飲品（非酒精）',
    mf_d7: '可連續預訂2小時',
    mf_d8: '更衣室、私人儲物櫃、AI賽事分析、聯賽及錦標賽',
    mf_d9: '免費使用DINK訓練角',
    mf_f1: '優先預訂——提前7天（繁忙及非繁忙時段）',
    mf_f2: '所有訂場享9折 + 社交賽享8折',
    mf_f3: '訓練期間可試用專業球拍',
    mf_f4: '優先參加社交活動及內部聚會',
    mf_f5: '零賓客費',
    mf_f6: '更衣室、私人儲物櫃、AI賽事分析、聯賽及錦標賽',
    mf_f7: '免費使用DINK訓練角',
    mf_nm1: '預訂限制——繁忙時段提前3天，非繁忙時段提前7天',
    mf_nm2: '球拍租借費 $20',
    mf_nm3: '標準訂場價格',
    mf_nm4: '每位賓客收取 $50 賓客費',
    mf_nm5: '更衣室使用權',

    // Book
    book_title: '預訂',
    book_hero: '預訂您的球場',
    book_select_court: '選擇球場',
    book_select_type: '選擇課程類型',
    book_select_date: '選擇日期',
    book_select_time: '可選時段',
    book_court1: '1號球場',
    book_court2: '2號球場',
    book_add_cart: '加入購物車',
    book_peak: '繁忙時段',
    book_nonpeak: '非繁忙時段',
    book_peak_desc: '週一至五 下午6時至晚上10時 · 週六、日及公眾假期 上午10時至晚上10時',
    book_nonpeak_desc: '週一至五 上午10時至下午6時',
    book_private_class: '私人課程',
    book_private_class_desc: '最多6名學員，配備國際認證教練',
    book_social: '社交賽',
    book_social_desc: '輕鬆對賽，結識新朋友',
    book_social_vip: '社交賽（會員）',
    book_trial: '體驗課',
    book_trial_desc: '每班最多8名學員（10歲或以上）',
    book_beginner: '初學者課程',
    book_beginner_desc: '4節課，配備認證教練',
    book_member_price: '會員優惠價',
    book_per_session: '/ 節',
    book_confirm: '確認預訂',
    book_guest_fee: '非會員需另加 $50 賓客費',
    book_member_badge: '會員',
    book_available: '有位',
    book_limited: '剩餘少量',
    book_full: '已滿',
    book_cart_added: '已加入購物車',

    // Social
    social_title: '社交賽',
    social_hero: '相遇。對賽。連繫。',
    social_desc: '社交賽是匹匠的核心——輕鬆、競技、充滿樂趣。隨時出現，即時配對，結識朋友。不需要球拍，不需要搭檔。',
    social_how_title: '社交賽運作方式',
    social_s1_title: '參加',
    social_s1: '預訂社交賽時段，無需搭檔，我們幫你配對。',
    social_s2_title: '配對',
    social_s2: '我們按水平分組，確保比賽平衡有趣。',
    social_s3_title: '對賽 · 連繫',
    social_s3: '認識新朋友，擴展人脈，享受比賽。',
    social_price_title: '社交賽收費',
    social_nonmember: '非會員',
    social_member: '會員優惠價',
    social_book: '預訂社交賽',

    // Private
    private_title: '私人及企業活動',
    private_hero: '私人活動及企業預訂',
    private_desc: '深受頂尖機構信賴，提供團隊建設活動、企業聚會及私人慶典。我們一手包辦——場地、教練、餐飲協調。',
    private_trusted: '合作夥伴',
    private_what_title: '我們提供',
    private_w1_title: '全場租用',
    private_w1: '為您的團隊提供獨家球場使用權，每節最多12名球員。',
    private_w2_title: '教練指導',
    private_w2: '國際認證教練為各水平球員提供系統化訓練。',
    private_w3_title: '度身訂造活動',
    private_w3: '錦標賽、聯賽及品牌活動，專為您的機構設計。',
    private_enquire: '立即查詢',
    private_class_price: '由 $1,060 起 / 節',

    // Contact
    contact_title: '聯絡我們',
    contact_hero: '與我們聯絡',
    contact_name: '您的姓名',
    contact_email: '電郵地址',
    contact_subject: '主題',
    contact_message: '訊息內容',
    contact_send: '發送訊息',
    contact_address_title: '位置',
    contact_address: '新界馬鞍山 We Go Mall',
    contact_hours_title: '開放時間',
    contact_hours: '週一至五：10:00–22:00\n週六、日及公眾假期：10:00–22:00',
    contact_follow: '追蹤我們',
    contact_sent: '訊息已發送，我們將盡快與您聯絡。',

    // Login / Account
    login_title: '登入',
    login_email: '電郵',
    login_password: '密碼',
    login_submit: '登入',
    login_register: '創建帳戶',
    login_forgot: '忘記密碼？',
    login_no_account: '還沒有帳戶？',
    register_title: '創建帳戶',
    register_name: '全名',
    register_email: '電郵',
    register_password: '密碼',
    register_submit: '創建帳戶',
    register_have_account: '已有帳戶？',
    account_welcome: '歡迎回來',
    account_member_status: '會員狀態',
    account_bookings: '我的預訂',
    account_no_bookings: '暫無即將到來的預訂。',
    account_book_now: '預訂課程',
    account_details: '帳戶資料',
    account_membership: '會員詳情',
    account_upgrade: '升級會員',

    // Cart
    cart_title: '購物車',
    cart_empty: '購物車是空的。',
    cart_total: '合計',
    cart_checkout: '結帳',
    cart_remove: '移除',
    cart_guest_note: '非會員每節需另加 $50 賓客費。',
    cart_member_disc: '已應用會員折扣。',
    checkout_title: '結帳',
    checkout_name: '持卡人姓名',
    checkout_card: '卡號',
    checkout_expiry: '到期日',
    checkout_cvc: '安全碼',
    checkout_pay: '立即付款',
    checkout_success: '預訂確認！',
    checkout_success_sub: '確認詳情已發送至您的電郵。',

    // More nav
    nav_more: '更多',
    nav_coaches: '教練團隊',
    nav_tournament: '錦標賽',
    nav_shop: '商店',
    nav_faq: '常見問題',

    // Coaches
    coaches_title: '教練團隊',
    coaches_hero: '認識我們的教練',
    coaches_sub: '我們的教練均持有國際認證，熱愛運動，致力幫助每位球員成長。',
    coaches_book: '預訂課程',
    coaches_inhouse: '駐場教練',
    coaches_flexible: '兼職教練',
    coaches_guest: '客席教練',

    // Tournament
    tournament_title: '錦標賽',
    tournament_hero: '競技·成長·勝利',
    tournament_sub: '匹匠定期舉辦內部錦標賽及聯賽，歡迎各水平球員參加。報名、競技、追蹤進步。',
    tournament_upcoming: '即將舉行的賽事',
    tournament_register: '立即報名',
    tournament_full: '已滿',
    tournament_open: '開放報名',
    tournament_members_only: '會員專屬',
    tournament_format: '賽制',
    tournament_level: '水平',
    tournament_date: '日期',
    tournament_fee: '報名費',

    // Shop
    shop_title: '商店',
    shop_hero: '裝備自己',
    shop_sub: '匹匠官方商品——球拍、服裝及配件。會員享有折扣。',
    shop_add: '加入購物車',
    shop_sold_out: '已售罄',
    shop_member_price: '會員價',
    shop_cat_paddles: '球拍',
    shop_cat_apparel: '服裝',
    shop_cat_accessories: '配件',
    shop_all: '全部',

    // FAQ
    faq_title: '常見問題',
    faq_hero: '常見問題',
    faq_sub: '首次到訪前，您需要知道的一切。',
    faq_still: '仍有疑問？',
    faq_contact: '聯絡我們',

    // Footer
    footer_about: '匹匠（Pickle Master）是香港頂級室內匹克球俱樂部。2026年成立。',
    footer_links: '快速連結',
    footer_legal: '法律條款',
    footer_privacy: '私隱政策',
    footer_terms: '服務條款',
    footer_cancel: '取消政策',
    footer_rights: '2026 Pickle Master。版權所有。',
    footer_payment: '接受付款方式',
  }
};

// Export to window
window.LANG = LANG;
